# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: frontend
#   annotations:
#     alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-1:023036697490:certificate/90d95497-a52a-4994-9768-6e6bb066a500
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
#     alb.ingress.kubernetes.io/ssl-redirect: "443"
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/healthcheck-path: /_healthz
#     alb.ingress.kubernetes.io/healthcheck-port: traffic-port
#     alb.ingress.kubernetes.io/success-codes: "200"
# spec:
#   ingressClassName: alb
#   rules:
#     - host: andrzejkl.site
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: frontend
#                 port:
#                   number: 8080
