apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend-resilience
spec:
  host: frontend.default.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3m
